<?xml version="1.0" encoding="utf-8"?><Database Name="CuaHang_XeMay_OFMain" Class="DataClassesQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAYTINH-9R2EF4H\SQLEXPRESS;Initial Catalog=CuaHang_XeMay_OFMain;Integrated Security=True" SettingsObjectName="QL_CuaHangXeMay.Properties.Settings" SettingsPropertyName="CuaHang_XeMay_OFMainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChucNang" Member="ChucNangs">
    <Type Name="ChucNang">
      <Column Name="ma_CN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_CN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ma_UI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChucNang_CT_Quyen" Member="CT_Quyens" ThisKey="ma_CN" OtherKey="ma_CN" Type="CT_Quyen" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_DM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_CT_PhieuNhap" Member="CT_PhieuNhaps" ThisKey="ma_SP" OtherKey="ma_SP" Type="CT_PhieuNhap" />
      <Association Name="SanPham_CTHD_BanHang" Member="CTHD_BanHangs" ThisKey="ma_SP" OtherKey="ma_SP" Type="CTHD_BanHang" />
      <Association Name="SanPham_Gia_SP" Member="Gia_SPs" ThisKey="ma_SP" OtherKey="ma_SP" Type="Gia_SP" />
      <Association Name="DanhMuc_SanPham" Member="DanhMuc" ThisKey="ma_DM" OtherKey="ma_DM" Type="DanhMuc" IsForeignKey="true" />
      <Association Name="Hang_SX_SanPham" Member="Hang_SX" ThisKey="ma_Hang" OtherKey="ma_Hang" Type="Hang_SX" IsForeignKey="true" />
      <Association Name="Loai_SP_SanPham" Member="Loai_SP" ThisKey="ma_Loai" OtherKey="ma_Loai" Type="Loai_SP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PhieuNhap" Member="CT_PhieuNhaps">
    <Type Name="CT_PhieuNhap">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gianhap_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_CT_PhieuNhap" Member="SanPham" ThisKey="ma_SP" OtherKey="ma_SP" Type="SanPham" IsForeignKey="true" />
      <Association Name="PhieuNhap_CT_PhieuNhap" Member="PhieuNhap" ThisKey="ma_PN" OtherKey="ma_PN" Type="PhieuNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_Quyen" Member="CT_Quyens">
    <Type Name="CT_Quyen">
      <Column Name="ma_NV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_CN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stas" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ChucNang_CT_Quyen" Member="ChucNang" ThisKey="ma_CN" OtherKey="ma_CN" Type="ChucNang" IsForeignKey="true" />
      <Association Name="NhanVien_CT_Quyen" Member="NhanVien" ThisKey="ma_NV" OtherKey="ma_NV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD_BanHang" Member="CTHD_BanHangs">
    <Type Name="CTHD_BanHang">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_CTHD_BanHang" Member="SanPham" ThisKey="ma_SP" OtherKey="ma_SP" Type="SanPham" IsForeignKey="true" />
      <Association Name="HD_BanHang_CTHD_BanHang" Member="HD_BanHang" ThisKey="ma_HD" OtherKey="ma_HD" Type="HD_BanHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD_DichVu" Member="CTHD_DichVus">
    <Type Name="CTHD_DichVu">
      <Column Name="ma_HDDV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_DV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gia_DV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_DV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_DV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_CTHD_DichVu" Member="DichVu" ThisKey="ma_DV" OtherKey="ma_DV" Type="DichVu" IsForeignKey="true" />
      <Association Name="HD_DichVu_CTHD_DichVu" Member="HD_DichVu" ThisKey="ma_HDDV" OtherKey="ma_HDDV" Type="HD_DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="ma_DM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_DM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DanhMuc_SanPham" Member="SanPhams" ThisKey="ma_DM" OtherKey="ma_DM" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="ma_DV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_DV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mota_DV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DichVu_CTHD_DichVu" Member="CTHD_DichVus" ThisKey="ma_DV" OtherKey="ma_DV" Type="CTHD_DichVu" />
      <Association Name="DichVu_Gia_DV" Member="Gia_DVs" ThisKey="ma_DV" OtherKey="ma_DV" Type="Gia_DV" />
    </Type>
  </Table>
  <Table Name="dbo.Gia_DV" Member="Gia_DVs">
    <Type Name="Gia_DV">
      <Column Name="ma_GiaDV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_DV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia_DV" Member="gia_DV1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_DBDV" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngay_KTDV" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DichVu_Gia_DV" Member="DichVu" ThisKey="ma_DV" OtherKey="ma_DV" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gia_SP" Member="Gia_SPs">
    <Type Name="Gia_SP">
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia_SP" Member="gia_SP1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngay_KTSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="SanPham_Gia_SP" Member="SanPham" ThisKey="ma_SP" OtherKey="ma_SP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hang_SX" Member="Hang_SXes">
    <Type Name="Hang_SX">
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_Hang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Hang_SX_SanPham" Member="SanPhams" ThisKey="ma_Hang" OtherKey="ma_Hang" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.HD_BanHang" Member="HD_BanHangs">
    <Type Name="HD_BanHang">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_KH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HD_BanHang_CTHD_BanHang" Member="CTHD_BanHangs" ThisKey="ma_HD" OtherKey="ma_HD" Type="CTHD_BanHang" />
      <Association Name="KhachHang_HD_BanHang" Member="KhachHang" ThisKey="ma_KH" OtherKey="ma_KH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HD_BanHang" Member="NhanVien" ThisKey="ma_NV" OtherKey="ma_NV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HD_DichVu" Member="HD_DichVus">
    <Type Name="HD_DichVu">
      <Column Name="ma_HDDV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_KH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HD_DichVu_CTHD_DichVu" Member="CTHD_DichVus" ThisKey="ma_HDDV" OtherKey="ma_HDDV" Type="CTHD_DichVu" />
      <Association Name="KhachHang_HD_DichVu" Member="KhachHang" ThisKey="ma_KH" OtherKey="ma_KH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HD_DichVu" Member="NhanVien" ThisKey="ma_NV" OtherKey="ma_NV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="ma_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mail_KH" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt_KH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="KhachHang_HD_BanHang" Member="HD_BanHangs" ThisKey="ma_KH" OtherKey="ma_KH" Type="HD_BanHang" />
      <Association Name="KhachHang_HD_DichVu" Member="HD_DichVus" ThisKey="ma_KH" OtherKey="ma_KH" Type="HD_DichVu" />
    </Type>
  </Table>
  <Table Name="dbo.Loai_SP" Member="Loai_SPs">
    <Type Name="Loai_SP">
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_Loai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Loai_SP_SanPham" Member="SanPhams" ThisKey="ma_Loai" OtherKey="ma_Loai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.Nha_CungCap" Member="Nha_CungCaps">
    <Type Name="Nha_CungCap">
      <Column Name="ma_NCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_NCC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Nha_CungCap_PhieuNhap" Member="PhieuNhaps" ThisKey="ma_NCC" OtherKey="ma_NCC" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="ma_NV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mail_NV" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt_NV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="mk_dangnhap" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="NhanVien_CT_Quyen" Member="CT_Quyens" ThisKey="ma_NV" OtherKey="ma_NV" Type="CT_Quyen" />
      <Association Name="NhanVien_HD_BanHang" Member="HD_BanHangs" ThisKey="ma_NV" OtherKey="ma_NV" Type="HD_BanHang" />
      <Association Name="NhanVien_HD_DichVu" Member="HD_DichVus" ThisKey="ma_NV" OtherKey="ma_NV" Type="HD_DichVu" />
      <Association Name="NhanVien_PhieuNhap" Member="PhieuNhaps" ThisKey="ma_NV" OtherKey="ma_NV" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_NCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylap_PN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhieuNhap_CT_PhieuNhap" Member="CT_PhieuNhaps" ThisKey="ma_PN" OtherKey="ma_PN" Type="CT_PhieuNhap" />
      <Association Name="Nha_CungCap_PhieuNhap" Member="Nha_CungCap" ThisKey="ma_NCC" OtherKey="ma_NCC" Type="Nha_CungCap" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuNhap" Member="NhanVien" ThisKey="ma_NV" OtherKey="ma_NV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CTHD" Method="CTHD">
    <ElementType Name="CTHDResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_DM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateSLT" Method="updateSLT">
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteLoaiSP" Method="DeleteLoaiSP">
    <Parameter Name="maloai" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_giasp_Price" Method="get_giasp_Price">
    <Parameter Name="giatu" Type="System.Int32" DbType="Int" />
    <Parameter Name="giaden" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_giasp_PriceResult">
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_giasp_Price_lonhon" Method="get_giasp_Price_lonhon">
    <Parameter Name="giatu" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_giasp_Price_lonhonResult">
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_GiaSPList" Method="Get_GiaSPList">
    <ElementType Name="Get_GiaSPListResult">
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_Hang_Loai" Method="get_Hang_Loai">
    <Parameter Name="tenhang" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="tenloai" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="get_Hang_LoaiResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_DM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Loai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Hang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_SanPhamList_Result" Method="Get_SanPhamList_Result">
    <ElementType Name="Get_SanPhamList_ResultResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Loai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Hang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDanhMucList" Method="getDanhMucList">
    <ElementType Name="getDanhMucListResult">
      <Column Name="ma_DM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_DM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getLoaiSPList" Method="getLoaiSPList">
    <ElementType Name="getLoaiSPListResult">
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_Loai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getMaSP" Method="getMaSP">
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <ElementType Name="getMaSPResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_DM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.hd_phieunhappppp" Method="hd_phieunhappppp">
    <ElementType Name="hd_phieunhapppppResult">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_NCC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_PN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.inPN" Method="inPN">
    <Parameter Name="mapn" Type="System.Int32" DbType="Int" />
    <ElementType Name="inPNResult">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_NCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylap_PN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ma_NV1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mail_NV" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt_NV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="mk_dangnhap" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ma_NCC1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NCC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ma_PN1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gianhap_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_SP1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_DM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.INSERT_CTHD" Method="INSERT_CTHD">
    <Parameter Name="mahd" Type="System.Int32" DbType="Int" />
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <Parameter Name="giasp" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="tongtien" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_HoaDon" Method="Insert_HoaDon">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Parameter Name="manv" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaylap" Type="System.DateTime" DbType="Date" />
    <Parameter Name="isdelete" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.search_hdBan" Method="search_hdBan">
    <Parameter Name="search" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="search_hdBanResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_hdpn" Method="search_hdpn">
    <Parameter Name="search" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="search_hdpnResult">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_NCC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_PN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SP" Method="search_SP">
    <Parameter Name="search" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="search_SPResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Loai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_Hang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.searh_giasp" Method="searh_giasp">
    <Parameter Name="search" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="searh_giaspResult">
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectAll_CTHD" Method="selectAll_CTHD">
    <Parameter Name="maHD" Type="System.Int32" DbType="Int" />
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectAll_CTHDResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectCTHD" Method="selectCTHD">
    <Parameter Name="mahd" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectCTHDResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectHoaDon" Method="selectHoaDon">
    <Parameter Name="mahd" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectHoaDonResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_KH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectSP" Method="selectSP">
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectSPResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_DM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateSL_CTHD" Method="updateSL_CTHD">
    <Parameter Name="ma" Type="System.Int32" DbType="Int" />
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="THANHTIEN" Parameter="tHANHTIEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.hd" Method="hd">
    <ElementType Name="hdResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.inHd" Method="inHd">
    <Parameter Name="mahd" Type="System.Int32" DbType="Int" />
    <ElementType Name="inHdResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt_KH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="mail_KH" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectPN" Method="selectPN">
    <Parameter Name="mapn" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectPNResult">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_NCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaylap_PN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.INSERT_PNHAP" Method="INSERT_PNHAP">
    <Parameter Name="MANHACUNGCAP" Parameter="mANHACUNGCAP" Type="System.Int32" DbType="Int" />
    <Parameter Name="MANHANVIEN" Parameter="mANHANVIEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="NGAYNHAP" Parameter="nGAYNHAP" Type="System.DateTime" DbType="Date" />
    <Parameter Name="isdelete" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.INSERT_CTPNHAPXE" Method="INSERT_CTPNHAPXE">
    <Parameter Name="MAPN" Parameter="mAPN" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASP" Parameter="mASP" Type="System.Int32" DbType="Int" />
    <Parameter Name="DONGIANHAPXE" Parameter="dONGIANHAPXE" Type="System.Int32" DbType="Int" />
    <Parameter Name="SLNHAPXE" Parameter="sLNHAPXE" Type="System.Int32" DbType="Int" />
    <Parameter Name="THANHTIEN" Parameter="tHANHTIEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.selectCTPNxe" Method="selectCTPNxe">
    <Parameter Name="ma" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectCTPNxeResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gianhap_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectCTPN" Method="selectCTPN">
    <Parameter Name="mapn" Type="System.Int32" DbType="Int" />
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectCTPNResult">
      <Column Name="ma_PN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gianhap_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateSLTCTPNX" Method="updateSLTCTPNX">
    <Parameter Name="ma" Type="System.Int32" DbType="Int" />
    <Parameter Name="masp" Type="System.Int32" DbType="Int" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="THANHTIEN" Parameter="tHANHTIEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThongKe_SPMuaNhieu" Method="ThongKe_SPMuaNhieu">
    <Parameter Name="month_Value" Type="System.Int32" DbType="Int" />
    <Parameter Name="year_Value" Type="System.Int32" DbType="Int" />
    <ElementType Name="ThongKe_SPMuaNhieuResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKe_Thang_Nam" Method="ThongKe_Thang_Nam">
    <Parameter Name="month_Value" Type="System.Int32" DbType="Int" />
    <Parameter Name="year_Value" Type="System.Int32" DbType="Int" />
    <ElementType Name="ThongKe_Thang_NamResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.tongdoanhthu" Method="tongdoanhthu">
    <ElementType Name="tongdoanhthuResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.xuatdata" Method="xuatdata">
    <ElementType Name="xuatdataResult">
      <Column Name="ma_HD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_HK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt_KH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="mail_KH" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_NV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaylap_HD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_giasp" Method="select_giasp">
    <ElementType Name="select_giaspResult">
      <Column Name="ma_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_DM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="soluong_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_SP1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia_SP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_BDSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngay_KTSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>