//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CuaHangXeMay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CuaHang_XeMay_OFMainEntities : DbContext
    {
        public CuaHang_XeMay_OFMainEntities()
            : base("name=CuaHang_XeMay_OFMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> ThongKe_Thang_Nam(Nullable<int> month_Value, Nullable<int> year_Value)
        {
            var month_ValueParameter = month_Value.HasValue ?
                new ObjectParameter("month_Value", month_Value) :
                new ObjectParameter("month_Value", typeof(int));
    
            var year_ValueParameter = year_Value.HasValue ?
                new ObjectParameter("year_Value", year_Value) :
                new ObjectParameter("year_Value", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ThongKe_Thang_Nam", month_ValueParameter, year_ValueParameter);
        }
    }
}
