//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Quyen
    {
        public int ma_NV { get; set; }
        public int ma_CN { get; set; }
        public Nullable<bool> stas { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
