//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD_BanHang
    {
        public int ma_HD { get; set; }
        public int ma_SP { get; set; }
        public Nullable<int> gia_SP { get; set; }
        public Nullable<int> soluong_SP { get; set; }
        public Nullable<int> tongtien_SP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual HD_BanHang HD_BanHang { get; set; }
    }
}
