//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD_DichVu
    {
        public int ma_HDDV { get; set; }
        public int ma_DV { get; set; }
        public Nullable<int> gia_DV { get; set; }
        public Nullable<int> soluong_DV { get; set; }
        public Nullable<int> tongtien_DV { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HD_DichVu HD_DichVu { get; set; }
    }
}
