//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gia_SP
    {
        public int ma_GiaSP { get; set; }
        public Nullable<int> ma_SP { get; set; }
        public Nullable<int> gia_SP1 { get; set; }
        public Nullable<System.DateTime> ngay_BDSP { get; set; }
        public Nullable<System.DateTime> ngay_KTSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
