//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHang_XeMayEntities : DbContext
    {
        public CuaHang_XeMayEntities()
            : base("name=CuaHang_XeMayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual DbSet<CT_Quyen> CT_Quyen { get; set; }
        public virtual DbSet<CTHD_BanHang> CTHD_BanHang { get; set; }
        public virtual DbSet<CTHD_DichVu> CTHD_DichVu { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<Gia_DV> Gia_DV { get; set; }
        public virtual DbSet<Gia_SP> Gia_SP { get; set; }
        public virtual DbSet<Hang_SX> Hang_SX { get; set; }
        public virtual DbSet<HD_BanHang> HD_BanHang { get; set; }
        public virtual DbSet<HD_DichVu> HD_DichVu { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Loai_SP> Loai_SP { get; set; }
        public virtual DbSet<Nha_CungCap> Nha_CungCap { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
